"""Structured audit trail for the agent backend.

Every request gets a `request_id` that ties together the incoming question,
every tool call/result (including the SQL text that actually ran, whether
issued directly or generated by Genie), the final answer, and token/cost
usage. Written as JSON Lines to `backend/logs/audit.jsonl` so an incident
("the agent told someone a wrong number last month") can be reconstructed
with a `grep <request_id>`.

This is deliberately a plain stdlib logger, not a metrics/observability
platform — the goal is a durable, greppable record, not dashboards.
"""

from __future__ import annotations

import json
import logging
import logging.handlers
from datetime import datetime, timezone
from pathlib import Path

_LOG_DIR = Path(__file__).parent / "logs"
_LOG_DIR.mkdir(exist_ok=True)

_logger = logging.getLogger("audit")
_logger.setLevel(logging.INFO)
_logger.propagate = False

if not _logger.handlers:
    file_handler = logging.handlers.RotatingFileHandler(
        _LOG_DIR / "audit.jsonl", maxBytes=20 * 1024 * 1024, backupCount=10
    )
    file_handler.setFormatter(logging.Formatter("%(message)s"))
    _logger.addHandler(file_handler)

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(logging.Formatter("%(message)s"))
    _logger.addHandler(console_handler)


def truncate(value, limit: int = 4000):
    """Caps long strings so one runaway field can't blow up the log line.
    Rows/columns from query results are summarized by callers, never dumped
    in full here, since they can carry customer-level fields (e.g. ehhn)."""
    if isinstance(value, str) and len(value) > limit:
        return value[:limit] + f"... [truncated, {len(value)} chars total]"
    return value


def log_event(event: str, **fields) -> None:
    record = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "event": event,
        **{k: v for k, v in fields.items() if v is not None},
    }
    _logger.info(json.dumps(record, default=str))


# Approximate published per-million-token USD rates. These are best-effort for
# cost *trending* in the audit trail, not billing-grade — update if pricing
# changes, and treat estimate_cost_usd's output as an estimate, not an invoice.
_PRICING_PER_MILLION_USD = {
    "claude-sonnet": {"input": 3.0, "output": 15.0, "cache_write": 3.75, "cache_read": 0.30},
    "claude-opus": {"input": 15.0, "output": 75.0, "cache_write": 18.75, "cache_read": 1.50},
    "claude-haiku": {"input": 0.80, "output": 4.0, "cache_write": 1.0, "cache_read": 0.08},
}
_DEFAULT_PRICING = _PRICING_PER_MILLION_USD["claude-sonnet"]


def _pricing_for(model: str) -> dict:
    for key, rates in _PRICING_PER_MILLION_USD.items():
        if key in model:
            return rates
    return _DEFAULT_PRICING


def estimate_cost_usd(model: str, usage: dict) -> float:
    rates = _pricing_for(model)
    input_tokens = usage.get("input_tokens", 0) or 0
    output_tokens = usage.get("output_tokens", 0) or 0
    cache_write = usage.get("cache_creation_input_tokens", 0) or 0
    cache_read = usage.get("cache_read_input_tokens", 0) or 0
    cost = (
        input_tokens * rates["input"]
        + output_tokens * rates["output"]
        + cache_write * rates["cache_write"]
        + cache_read * rates["cache_read"]
    ) / 1_000_000
    return round(cost, 6)
